### ISSUE TITLE
Requires Actuator?

### ISSUE THREAD

**Issue by tomwhoiscontrary** [spring-cloud/spring-cloud-bus#10]
I've put together a trivial project which uses spring-cloud-starter-bus-amqp 1.0.0.RC1:

https://github.com/tomwhoiscontrary/BusSpike

Commit 2061bc644ace0fe87b71033a1c71b5ff6380b388 has the Cloud Bus starter and Actuator, and works - it builds and boots. However, if i remove the dependency on Actuator, boot fails like this:

https://gist.github.com/tomwhoiscontrary/748e4006ac2de424b241

Where i think the root cause is "java.lang.IllegalArgumentException: @ConditionalOnMissingBean annotations must specify at least one bean (type, name or annotation)", although i'm not at all sure.

The test fails in a corresponding way.

Does Cloud Bus require Actuator? If so, should there be an explicit dependency on it? If not, is there a bug to be fixed here? If not, is there something that i should change in my code, and which should be documented somewhere?

**Comment by spencergibb** [comment]
It currently does require actuatuor.  I don't think it needs to be.  You should be able to bind to the bus (without actuator) and respond to events even though you can't use the built in actuator endpoints (`/bus/refresh` and `/bus/env`. 

Thanks for the issue.

**Comment by dsyer** [comment]
I'm looking at this. Wondering why you would want to use a bus without the endpoints (you'd have to build and send the events manually I guess).

Having some issues debugging the reflection issues as well, so I'd be quite happy not to have to continue.

**Comment by spencergibb** [comment]
@dsyer custom events come to mind.

**Comment by tomwhoiscontrary** [comment]
Yep, custom events. There are a variety of things where we want to say "all instances, do X", and this seems like the ideal way to do it.

In practice, we will probably have Actuator as well. But i started off with a spike, trying to make it as minimal as possible, so didn't include Actuator, and got the rather baffling error.

**Comment by dsyer** [comment]
The baffling error is nothing to do with Spring Cloud really (the JDK, Spring and Spring Boot all try to make something of it, but none succeed). But I'll spend a few more cycles on it, and maybe I can hack it out eventually.
