### ISSUE TITLE
ContentTypeConfiguration init before BusJacksonAutoConfiguration

### ISSUE THREAD

**Issue by yanghongge** [spring-cloud/spring-cloud-bus#100]
spring-boot-starter-parent 2.0.0.M7 with spring-cloud-dependencies Finchley.BUILD-SNAPSHOT

CompositeMessageConverterFactory 's converters only contain 7  MessageConverter,  no  busJsonConverter, so  RefreshRemoteApplicationEvent convert error.

**Comment by spencergibb** [comment]
M7 and snapshots don't go together. Can you try with boot snapshots?

**Comment by yanghongge** [comment]
Firstly, thank you so much for reply.

It still doesn't work.

In spring-cloud-bus-1.3.0 
CompositeMessageConverterFactory init in BindingServiceConfiguration,
BindingServiceConfiguration.customMessageConverters contains 2 MessageConverter:
DefaultDatatypeChannelMessageConverter  And  BusJacksonMessageConverter

In Finchley.BUILD-SNAPSHOT
CompositeMessageConverterFactory init in ContentTypeConfiguration,
but the customMessageConverters is null,

so,/actuator/bus-refresh -> Could not resolve type id 'RefreshRemoteApplicationEvent' as a subtype, with no BusJacksonMessageConverter

Thank you for taking time help.

**Comment by spencergibb** [comment]
spring-cloud-bus 1.3.x is not compatible with finchley. You need to use 2.0.0.BUILD-SNAPSHOTS

**Comment by spencergibb** [comment]
Fixed via  e57a404
