### ISSUE TITLE
Local RemoteApplicationEvents are not recognized due to inconsistent contextId and serviceId, which prevents sending them to the outbound channel

### ISSUE THREAD

**Issue by iabudiab** [spring-cloud/spring-cloud-bus#105]
It seem that the new contextId generation logic introduced in [spring-boot#11023](https://github.com/spring-projects/spring-boot/issues/11023) broke the [ServiceMatcher's](https://github.com/spring-cloud/spring-cloud-bus/blob/e57a4047959671b513d345344b2729a96f92a473/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/ServiceMatcher.java#L36) check for own local events.

In the matcher the `serviceId` is handled correctly, as far as I can see. However the `originService` gets the `-1` suffix, hence the mismatch. For example, if `spring.application.name` is `configserver` then the `originService` of the event is `configserver-1`

This results in local `RemoteApplicationEvents` being ignored [in the listener](https://github.com/spring-cloud/spring-cloud-bus/blob/509a216258cdd071c592bc921b83e979d3f0944d/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/BusAutoConfiguration.java#L119). 

I am guessing that the context is initialized twice. Once via the `BootstrapApplicationListener` and once via the `prepareContext` in `SpringApplication`. Which leads to adding the "-1" suffix as described in [spring-boot#11023](https://github.com/spring-projects/spring-boot/issues/11023)

The only way to get `RemoteApplicationEvents` sent is to add the "-1" suffix to the `spring.bus.id`

Here is a minimal config server/client sample project demonstrating the issue: [Sample](https://github.com/iabudiab/spring-config-server-sample)

Let me know if you need any more input.

**Comment by spencergibb** [comment]
It's not the boot change since bus changed and doesn't use application context I'd anymore. Thanks for the sample, we'll take a look.

**Comment by spencergibb** [comment]
Can you please describe the steps to replicate the issue? There are no instructions.

**Comment by iabudiab** [comment]
@spencergibb Sure. Here are the steps to test/reproduce:

- Start a rabbit instance and the `config-server-sample`
- Create `config-client-sample.yml` under `/tmp/config-sample`:

```yml
# config-client-sample.yml
greeting: Hello
```

- Start the `config-client-sample`and `GET :3000/` You'll get the value in the `greeting` property
- Now change the value in the configuration file (`/tmp/config-sample/config-client-sample.yml`) to something else
  - The config server will pick this change and broadcast an event
  - The config client will retrieve the new value and return it on subsequent GET requests

**Now the Bug**:
- Change the value of `spring.cloud.bus.id` in the `bootstrap.yml` of the `config-server-sample` to anything other than `config-server-sample-1`
- Config server wont send any RemoteApplicationEvents when changing the `greeting` property in `config-client-sample.yml`

More generally, if the value of `spring.cloud.bus.id` is not `${spring.application.name}-1` the `RemoteApplicationEvents` wont be sent

Please let me know if you need anything else.

I could provide a `docker-compose` to streamline this process if you want, however I wont be able to do it till later today or tomorrow.

**Comment by spencergibb** [comment]
OK, multiple issues going on here.

1. deriving application names from files assume the application name doesn't have a dash `-` in it (since profiles follow dashes). Changing `spring.application.name` from `config-client-sample` to `configclientsample` and renaming the file in `/tmp/config-sample` fixed that problem.
2. The bus `RefreshListener` required actuator to be on the classpath, I am fixing that.

**Comment by iabudiab** [comment]
@spencergibb This doesn't solve the whole issue. 

The config server is still not sending the refresh event to the clients, because the check in the [EventListener in the Config Server](https://github.com/spring-cloud/spring-cloud-bus/blob/509a216258cdd071c592bc921b83e979d3f0944d/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/BusAutoConfiguration.java#L119) fails. Thus the following statement in the config server [`this.cloudBusOutboundChannel.send(MessageBuilder.withPayload(event).build());`](https://github.com/spring-cloud/spring-cloud-bus/blob/509a216258cdd071c592bc921b83e979d3f0944d/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/BusAutoConfiguration.java#L121) is never executed. 

The check fails because the `serviceId` and the `originService` in the [ServiceMatcher](https://github.com/spring-cloud/spring-cloud-bus/blob/e57a4047959671b513d345344b2729a96f92a473/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/ServiceMatcher.java) do not match.

**Comment by spencergibb** [comment]
Why does the config server need the event? The event is for the client.

**Comment by spencergibb** [comment]
With the changes I outlined above, the configclientsample was receiving remote refresh events just fine.

**Comment by iabudiab** [comment]
@spencergibb The problem is with the event that is intended for the client but originated in the server. This is the broadcast functionality of the config server when it detects any configuration changes. See the reference documentation about [Push Notifications and Spring Cloud Bus](http://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.0.0.M9/single/spring-cloud-config.html#_push_notifications_and_spring_cloud_bus)

As in:
- Server detects config change
- Server broadcasts refresh event to the clients
- Clients reload their configs from the server

The bug is in this broadcast handling, i.e. **the broadcast event is never sent from the server to the clients** due to the failed checks as I've described in previous comments.

The fix you provided solves the issue with the client not receiving remote refresh events that reached the binder.

The issue I am describing is, that the refresh events from the server never reach the binder.

Let me know if you need any further clarification.

**Comment by spencergibb** [comment]
And I'm saying those events came from config server. I don't understand what isn't happening now.

**Comment by iabudiab** [comment]
@spencergibb Glad we understood each other. I wont be able to comment till tomorrow, it's almost 1am here in Germany. But please let me know if I can help in any further.

**Comment by spencergibb** [comment]
Thanks for being patient with me. Fix coming later tonight (it's done but not unit tested).
