### ISSUE TITLE
Bus and Zipkin are used simultaneously in the project, causing engineering links to be less than zipken

### ISSUE THREAD

**Issue by 544845389** [spring-cloud/spring-cloud-bus#110]
![8 prqcy z47b373b brg](https://user-images.githubusercontent.com/27183580/37711563-1ae18b60-2d4c-11e8-82c4-f52893545e36.png)

![ixqcnct2 n 6xkem rk2](https://user-images.githubusercontent.com/27183580/37711638-4efb1a4c-2d4c-11e8-87c5-8741beda22f1.png)

**Comment by spencergibb** [comment]
Please don't use screenshots. I don't understand the problem because you have not described it. What versions are you using?

**Comment by 544845389** [comment]
Sorry, English is not very good. It may not be well described.

Bus and spring-cloud-zipkin are used at the same time in one project.

Join <dependency>

<groupId>org.springframework.cloud</groupId>

<artifactId>spring-cloud-starter-buamqp</artifactId>

</dependency>

After that, the project is not connected to the Zipkin. Zipkin is started in the way of http: @EnableZipkinServer

**Comment by 544845389** [comment]
Sorry, English is not very good. It may not be well described.

Bus and spring-cloud-zipkin are used at the same time in one project.

Join <dependency>

<groupId>org.springframework.cloud</groupId>

<artifactId>spring-cloud-starter-buamqp</artifactId>

</dependency>

After that, the project is not connected to the Zipkin. Zipkin is started in the way of http: @EnableZipkinServer

**Comment by 544845389** [comment]
Sorry, English is not very good. It may not be well described.
Bus and spring-cloud-zipkin are used at the same time in one project.
Join 
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-buamqp</artifactId>
</dependency>
After that, the project is not connected to the Zipkin. Zipkin is started in the way of http: @EnableZipkinServe

**Comment by spencergibb** [comment]
My guess is you have a corrupted dependency as bus had no bearing on sleuth or zipkin.
