### ISSUE TITLE
Custom RemoteApplicationEvent to receive multiple events?

### ISSUE THREAD

**Issue by 65725738** [spring-cloud/spring-cloud-bus#116]
The same event message has been received many times.Using kafka as a message broker.

log：
   16:09:13.094 logback-auth-server [-L-1] INFO  c.b.i.a.s.aa.CacheChangeListener - ###############################{profileId=2}
16:09:13.094 logback-auth-server [-L-1] INFO  c.b.iot.auth.server.aa.AACacheUtil - ####################################################refreshUserBase profileId:2
16:09:13.102 logback-auth-server [-L-1] INFO  c.b.i.a.s.aa.CacheChangeListener - ###############################{profileId=2}
16:09:13.102 logback-auth-server [-L-1] INFO  c.b.iot.auth.server.aa.AACacheUtil - ####################################################refreshUserBase profileId:2
16:09:13.121 logback-auth-server [-L-1] INFO  c.b.i.a.s.aa.CacheChangeListener - ###############################{profileId=2}
16:09:13.121 logback-auth-server [-L-1] INFO  c.b.iot.auth.server.aa.AACacheUtil - ####################################################refreshUserBase profileId:2
16:09:13.131 logback-auth-server [-L-1] INFO  c.b.i.a.s.aa.CacheChangeListener - ###############################{profileId=2}
16:09:13.131 logback-auth-server [-L-1] INFO  c.b.iot.auth.server.aa.AACacheUtil - ####################################################refreshUserBase profileId:2

pom：

		<dependency>
		    <groupId>org.springframework.kafka</groupId>
		    <artifactId>spring-kafka</artifactId>
		</dependency>

            <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-bus-kafka</artifactId>
			<optional>true</optional>
			<exclusions>
			    <exclusion>
			      <groupId>org.apache.kafka</groupId>
			      <artifactId>kafka_2.11</artifactId>
			    </exclusion>
		  </exclusions>
		</dependency>

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
    </parent>

          <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

**Comment by spencergibb** [comment]
Is this still an issue?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
