### ISSUE TITLE
how to solve /monitor endpoint does not notify Spring Cloud Config Client in Finchley.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by cs1145461707** [spring-cloud/spring-cloud-bus#120]
Hello there, 
Someone has issued the same quest before: https://github.com/spring-cloud/spring-cloud-bus/issues/112.

Today I met again:
I have added spring-cloud-config-monitor to call /monitor endpoint via webhook, however the config client does not refresh the configuration when the webhook is triggered.
I also have exposed the /actuator/bus-refresh endpoint to make local test and this works perfectly.

spring version:
spring-boot: 2.0.2.RELEASE
spring-cloud: Finchley.BUILD-SNAPSHOT
Here's my code:

Config server : https://github.com/cs1145461707/config
Config Client: https://github.com/cs1145461707/client
Eureka Server: https://github.com/cs1145461707/eureka
git which has config files: https://github.com/cs1145461707/config-repo

Spencergibb has answered this question, that's it's caused by name mismatching.
Then someone in the article, which is above links refers to, said his application name didn't have a dash in it. But the dashes in app name is getting added via spring cloud jars ：

 `2018-04-19 19:05:26.352  INFO 67226 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'rickle-1-1.sunand.anonymous.1D6VdnJWQrqyyDVKPlvi4A.errors' has 1 subscriber(s).
2018-04-19 19:05:26.352  INFO 67226 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'rickle-1-1.sunand.anonymous.1D6VdnJWQrqyyDVKPlvi4A.errors' has 2 subscriber(s).
2018-04-19 19:05:26.370 `

Considering all from the 112 issue and what i met, right now I am confused about how to solve this problem, what is the sulution? Can you please let us know how to correct this?

**Comment by lly835** [comment]
see https://github.com/spring-cloud/spring-cloud-bus/issues/124
