### ISSUE TITLE
RemoteApplicationEvent publish  give me troubles 

### ISSUE THREAD

**Issue by weirui** [spring-cloud/spring-cloud-bus#121]
when i click the /bus/refresh?destination=ap:898 or /bus/env?destination=ap:8 ,the local RefreshListener.class will receive  the refresh event. it  bypass the destinnation match;

application publish will  trigger the action;
should directly publish broker.

@ManagedResource
public class RefreshBusEndpoint extends AbstractBusEndpoint {

	public RefreshBusEndpoint(ApplicationEventPublisher context, String id,
			BusEndpoint delegate) {
		super(context, id, delegate);
	}

	@RequestMapping(value = "refresh", method = RequestMethod.POST)
	@ResponseBody
	@ManagedOperation
	public void refresh(
			@RequestParam(value = "destination", required = false) String destination) {
		publish(new RefreshRemoteApplicationEvent(this, getInstanceId(), destination));
	}

}

**Comment by spencergibb** [comment]
All refresh events will be handled by the service that receives them because they are normal Spring ApplicationEvents. Not sure there is much I can do about it.

**Comment by weirui** [comment]
> All refresh events will be handled by the service that receives them because they are normal Spring ApplicationEvents. Not sure there is much I can do about it.

this my understand of remote Spring  application Event.

 first， Something actions may trigger Spring application Event .
second ，the event  is broadcasted to message  queue ,when the event is remote event .
third ， some service instance can receives them and do some special action .

the problem is that service instance can receives the Spring application  event before step two.

the problem cause  the service instance which  triggers the Spring application event refresh two times.

**Comment by spencergibb** [comment]
Duplicates #68
