### ISSUE TITLE
springBus override all inputBindings in InputBindingLifecycle

### ISSUE THREAD

**Issue by tlabossa** [spring-cloud/spring-cloud-bus#126]
SpringBoot 2.0.3.RELEASE
SpringCloud Finchley.RELEASE

We want to use /actuator/binding lifeCycle to start and stop bindings but if using springCloudBus only bus is visible all other disapear.

**Comment by spencergibb** [comment]
Can you describe the problem more? We don't do anything specific with the stream actuator.

**Comment by tlabossa** [comment]
Without bus dependency after calling /actuator/binding I got correctly my 2 test bindings and I can manage it start and stop binding.
![image](https://user-images.githubusercontent.com/40788877/42218788-fbb7245a-7ec9-11e8-8635-da8ac78930e5.png)

Adding bus dependeny only got springCloudBus binding without my 2 test bindings
![image](https://user-images.githubusercontent.com/40788877/42218867-3b871c3e-7eca-11e8-9be2-17ca027d665d.png)



Here is my application.yml
![image](https://user-images.githubusercontent.com/40788877/42218916-631c8de2-7eca-11e8-947e-edfc55caa981.png)

**Comment by tlabossa** [comment]
After this call all inbutBinding will be removed and only springCloud binding remains
![image](https://user-images.githubusercontent.com/40788877/42219132-13e365ce-7ecb-11e8-8943-52fb7f395cae.png)

**Comment by spencergibb** [comment]
Can you please try with the latest Finchley.SR2 and boot 2.0.8 or Greenwich.RELEASE and boot 2.1.2

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
