### ISSUE TITLE
bus/refresh client can't autoupdate

### ISSUE THREAD

**Issue by Gaodongove** [spring-cloud/spring-cloud-bus#130]
confid-server dependence:
![2018-08-03_093511](https://user-images.githubusercontent.com/33369162/43619507-c4cfb8ea-9700-11e8-83a6-10988813fc59.png)

application.yml:
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Gaodongove/springcloud-test.git
          username: ******
          password: *******
          search-paths: '{profile}'
          basedir: F:/temp
    bus:
      trace:
        enabled: true
      enabled: true
  rabbitmq:
    host: *****
    port: 5672
    username: guest
    password: guest
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

github webhooks:
![2018-08-03_093739](https://user-images.githubusercontent.com/33369162/43619555-1ea67d5e-9701-11e8-8e15-836d5e3b26c7.png)
![2018-08-03_093757](https://user-images.githubusercontent.com/33369162/43619556-2172356e-9701-11e8-8366-192e309348ca.png)

config-server log:
![2018-08-03_094017](https://user-images.githubusercontent.com/33369162/43619645-79663b08-9701-11e8-84a1-b287e6c7b7ad.png)
 but config-client notanything,when i request url,properties is not update,

**Comment by spencergibb** [comment]
Have you tried with the latest versions of boot 2.0.6 and Finchley.SR2?

**Comment by bacelchen** [comment]
> Have you tried with the latest versions of boot 2.0.6 and Finchley.SR2?

yes,2.0.7.RELEASE and Finchley.SR2,is ok!! thks~

**Comment by 1060352728** [comment]
Thank you. The problem has been solved， use bus-id ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}:${vcap.application.instance_id:${random.value}}


------------------ 原始邮件 ------------------
发件人: "Spencer Gibb"<notifications@github.com>;
发送时间: 2018年12月10日(星期一) 上午10:50
收件人: "spring-cloud/spring-cloud-bus"<spring-cloud-bus@noreply.github.com>;
抄送: "李奎"<1060352728@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [spring-cloud/spring-cloud-bus] bus/refresh client can'tautoupdate (#130)




Closed #130.
