### ISSUE TITLE
spring cloud bus cant sent message to chennal

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-bus#136]
spring cloud version：Finchley.SR1

BusEvent busEvent = new BusEvent(event, serviceId, "*:**");
		// publish
		applicationContext.publishEvent(busEvent);

in class **BusAutoConfiguration** 。the code _this.serviceMatcher.isFromSelf(event)_ always return **false** ，why？

**Comment by ExtremeYu** [comment]
hi，i don't know what the following code wahts to do？


**DefaultBusPathMatcher**

@Override
	public boolean match(String pattern, String path) {
		log.debug("In match: " + pattern + ", " + path);
		if (!delagateMatcher.match(pattern, path)) {
			return matchMultiProfile(pattern, path);
		}
		return true;
	}

**Comment by ryanjbaxter** [comment]
Please learn how to [format code on GitHub](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Can you please write a description of what you are trying to do and what the problem is?  Pasting in random code snippets is not very useful.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by ExtremeYu** [comment]
i found why
![image](https://user-images.githubusercontent.com/16620268/47330678-b2a96e00-d6ab-11e8-9bdd-f00a46c6dc9b.png)

you should use spring boot own id to send your meessage

**Comment by renatojava** [comment]
Hello,

I've had the same problem, before this works with the code below?
```java
    public static void publishNotificationTest() {
        var context = StaticApplicationAcessor.getApplicationContext();
        StaticApplicationAcessor.getApplicationContext().publishEvent(new NotificationRemoteEvent(Notification.builder().build(), context.getId()));
    }
```
Where the class constructor:
 public NotificationRemoteEvent(Notification source, String **originService**) {

But now the **context.getId() -> applicationContext** doesn't work, I needed get the BusProperties.getId, 
Why it does not this work anymore with applicationContext.getId() for serviceId?

Many thanks.
