### ISSUE TITLE
Question about stream binder like queue for streamListener

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-bus#145]
There is some questions about below code. From my understanding, when I want to `POST` to `/actuator/bus-refresh` of config-server, the config-server itself can also receive the data too. If not from config-server, it will publish this event to stream. My question is about how that works if the stream queue message will be delete (like spring-cloud-azure-servicebus-queue-stream-binder) once it received, if we do not delete that received message, which means other client can receive that forever ?

https://github.com/spring-cloud/spring-cloud-bus/blob/fd827e8e8bf2ed53c678d2957a18a3461cb5b27a/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/BusAutoConfiguration.java#L148-L162

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
