### ISSUE TITLE
/actuator/bus-refresh is not exposed with spring-boot-admin-starter-client

### ISSUE THREAD

**Issue by guerricm** [spring-cloud/spring-cloud-bus#146]
Bug report
spring-cloud-version: Greenwich.RC2
spring-boot-version: 2.1.2.RELEASE
spring-boot-admin-version: 2.1.1

here is an example :
https://github.com/guerricm/spring-cloud-config-bus-refresh-example.git

if you comment in the pom.xml of `department-service` or `employee-service`
```
<dependency>
	<groupId>de.codecentric</groupId>
	<artifactId>spring-boot-admin-starter-client</artifactId>
</dependency>
```
applications expose the actuator `/bus-refresh`
![image](https://user-images.githubusercontent.com/20113664/51541311-ce621300-1e58-11e9-86a9-f793f6b2adf5.png)

if you uncomment the dependency  `spring-boot-admin-starter-client`, the actuator is not exposed

**Comment by spencergibb** [comment]
Sorry, we don't maintain spring-boot-admin. You'll need to open an issue there.
