### ISSUE TITLE
Time cannot be sequenced to timestamp after using AMQP dependencies

### ISSUE THREAD

**Issue by hoboC** [spring-cloud/spring-cloud-bus#147]
Question：Time cannot be sequenced to timestamp after using 

`spring-cloud-starter-bus-amqp`

dependencies
I also used the following configuration, but it didn't work. My spring cloud version is Finchley.SR1 and spring boot version is 2.0.3.RELEASE;

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

**Comment by spencergibb** [comment]
You need to explain better what is happening. Can you show an example?

**Comment by hoboC** [comment]
[This is a example](https://github.com/hoboC/demo.git)
When the spring-cloud-starter-bus-amqp dependency is introduced, the following configuration will have no effect.
this is configuration:
`
spring:
  jackson:
    serialization:
       WRITE_DATES_AS_TIMESTAMPS: true
`
             How to solve this problem ? I want to serialize the date as a timestamp, not a time.
             I would like to return to the following:
	         {
	             "time":"1548740817"
	         }
	         not this:
	         {
	             "time":"2019-1-29 13:46:57:0"
	         }

**Comment by spencergibb** [comment]
For some reason it is hard coded

https://github.com/spring-cloud/spring-cloud-bus/blob/bbd87c3eced3f049897136c99e63bdccfa7f4c8f/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/jackson/BusJacksonAutoConfiguration.java#L192-L195

**Comment by xiaobai-tx** [comment]
> For some reason it is hard coded
> 
> https://github.com/spring-cloud/spring-cloud-bus/blob/bbd87c3eced3f049897136c99e63bdccfa7f4c8f/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/jackson/BusJacksonAutoConfiguration.java#L192-L195

Is it ready to be configured?
