### ISSUE TITLE
auto refresh configuration doesn't work when i use github webhook

### ISSUE THREAD

**Issue by yanglikun** [spring-cloud/spring-cloud-bus#152]
spring boot version：2.1.3.RELEASE
spring cloud version：Greenwich.RELEASE

In my computer，after I access the URL：http://127.0.0.1:8080/actuator/bus-refresh，the configuration can auto refresh.

when I use github webhook，It seems that spring can't parse the github payload.
![image](https://user-images.githubusercontent.com/1728527/54082453-15e12780-4351-11e9-8f91-6f3968be0029.png)
the response is：
`{"timestamp":"2019-03-10T04:47:52.685+0000","status":400,"error":"Bad Request","message":"JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token\n at [Source: (PushbackInputStream); line: 1, column: 301] (through reference chain: java.util.LinkedHashMap[\"commits\"])","path":"/actuator/bus-refresh"}`

I saw  the '/actuator/monitor' url  in other answers，Though the response is 200 ,but the configuration is not refresh.

**Comment by spencergibb** [comment]
Can you try with Greenwich.SR1?

**Comment by yanglikun** [comment]
> Can you try with Greenwich.SR1?

The Greenwich.SR1 version does not work either, the error message is the same.
It seems that spring can't parse the github payload.
The backend log is as follows：
`2019-03-20 11:19:50.383|||http-nio-8080-exec-5|WARN |o.s.w.s.m.s.DefaultHandlerExceptionResolver[AbstractHandlerExceptionResolver.java:197]|Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_ARRAY token
 at [Source: (PushbackInputStream); line: 1, column: 301] (through reference chain: java.util.LinkedHashMap["commits"])]`

**Comment by spencergibb** [comment]
github webhook should point to /monitor not /bus-refresh

**Comment by Xiaotian0626** [comment]
大哥，你的问题最后是怎么解决的？我也遇到一样的问题。
