### ISSUE TITLE
Make Bus endpoints addressable by service ID

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-bus#17]
I think the intention all along was probably to make Bus endpoints addressable by service ID, but currently they are only addressable by `ApplicationContext` ID.

**Comment by spencergibb** [comment]
originally it was, but morphed without a test that failed :-(

**Comment by dsyer** [comment]
We probably need to change the message payloads so that the service ID is available (if there is one) in addition to the context ID. Maybe add some more metadata from discovery as well if it exists.
