### ISSUE TITLE
Condition Evaluation report log property of Automatic Restart not working

### ISSUE THREAD

**Issue by leggiero** [spring-cloud/spring-cloud-bus#190]
Setting `spring.devtools.restart.log-condition-evaluation-delta=false` in application.properties do not prevent the Condition Evaluation report to be writing to the log output.

[20.2.1 Logging changes in condition evaluation](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-restart-logging-condition-delta)

Note that I have `debug=true` as I'm running the application in my development environment.

As a workaround, I'm setting `logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener=INFO`. This should be avoided by using the correct property to disable the report.

The application restart is working properly.
I'm using Spring Boot **2.1.4.RELEASE**.

Could you guys, please have a look?

Thank you.

**Comment by spencergibb** [comment]
What does this have to do with bus?

**Comment by leggiero** [comment]
Sorry, opened in the wrong project: reopened in Spring Boot: https://github.com/spring-projects/spring-boot/issues/16578
