### ISSUE TITLE
Enhance spring bus to provide a trace endpoint

### ISSUE THREAD

**Issue by vibhortayal** [spring-cloud/spring-cloud-bus#193]
The bus had a custom trace that is now broken since maps are no longer used.
https://github.com/spring-cloud/spring-cloud-commons/issues/311

Submission of Pull Request in progress.

**Comment by ryanjbaxter** [comment]
So is this an implementation of what @spencergibb proposed in spring-cloud/spring-cloud-commons#311?  If so we need an abstraction in spring-cloud-commons first.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by vibhortayal** [comment]
Should we put it in spring cloud commons or in spring cloud bus? Could you explain a bit more what you mean by "abstraction in spring-cloud-commons first."?

**Comment by spencergibb** [comment]
It should be in commons where I proposed it.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
