### ISSUE TITLE
Is it possible to integrate RocketMQ for configuration refresh?

### ISSUE THREAD

**Issue by qiaoqiao888** [spring-cloud/spring-cloud-bus#196]
Is it possible to integrate RocketMQ for configuration refresh?

**Comment by spencergibb** [comment]
If there is a rocketmq spring cloud stream binder, then yes. Looks like there is here https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-stream-binder-rocketmq

**Comment by qiaoqiao888** [comment]
The problem has been solved. Thank you.
