### ISSUE TITLE
spring-cloud-bus doesnt work with nacos config

### ISSUE THREAD

**Issue by JunRzz** [spring-cloud/spring-cloud-bus#198]
Hello,Recently，Im trying to update my spring cloud project to Greenwich.SR1 and using Nacos as my discovery and config server.In the previous code,I had a custom event which used spring cloud bus to synchronize the local cache.But I found when I use nacos config server,the custom event cannot be sent through rabbitmq,and only the sender can receive the event.and if I remove the nacos config,it will be fine.so I want to ask is there have some ways to resolve this?

**Comment by ryanjbaxter** [comment]
I would start by opening an issue in spring-cloud-alibaba.  I am not sure there is anything in your description that actually points to an issue with spring-cloud-bus.
