### ISSUE TITLE
RefreshListener bean is not registered

### ISSUE THREAD

**Issue by vyletpet** [spring-cloud/spring-cloud-bus#199]
Hello!

After update to 2.1 version of spring-cloud-bus (using Greenwich release) application context refresh functionality stop working. We tracked the issue down and found out that RefreshListener bean is not registered because the bean condition @ConditionalOnBean(ContextRefresher.class) is evaluated as false even though RefreshAutoConfiguration is initialised.

As a workaround we override the RefreshListener bean definition with a one without the context refresh conditional and everything works again.

As a root cause I see the missing auto-config order definition
@AutoConfigureAfter(name = {"org.springframework.cloud.autoconfigure.RefreshAutoConfiguration"})
that used to be defined in 2.0 version BusRefreshAutoConfiguration but it is no longer defined in version 2.1 BusAutoConfiguration.

I was trying to setup a test for that but as it seems to be connected with the auto-config processing order I was not able to simulate this issue in a simple scenario.

**Comment by spencergibb** [comment]
Can you please retry with Greenwich.SR1

**Comment by vyletpet** [comment]
Yes, the situation is the same for Greenwich.SR1 and all Spring Cloud Bus 2.1.x versions available at the moment. 

Anyway was there any reason for removal of 
@AutoConfigureAfter(name = {"org.springframework.cloud.autoconfigure.RefreshAutoConfiguration"})
for RefreshListener?

**Comment by spencergibb** [comment]
So you are unable to create a project that recreates the problem?

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
