### ISSUE TITLE
Update spring.io/projects/spring-cloud-bus to mention integration with Spring Cloud Stream

### ISSUE THREAD

**Issue by elefeint** [spring-cloud/spring-cloud-bus#203]
From Spring Cloud Bus main [configuration page](https://github.com/spring-cloud/spring-cloud-bus/blob/master/docs/src/main/asciidoc/sagan-index.adoc): 

> The only implementation currently is with an AMQP broker as the transport

But because Spring Cloud Bus integrates with any Spring Cloud Stream Binder, it can actually work on any transport. This information is available in [QuickStart](https://github.com/spring-cloud/spring-cloud-bus/blob/ffb17c91d87d119cf562c34b342ade71e9e5ac6a/README.adoc#quick-start), but people might not get that far if they see only AMQP as the transport on the main project page. 

Would it make sense to do one or both of the following:
1) Replace "The only implementation currently is with an AMQP broker as the transport," with "AMQP and Kafka broker implementations are included with the project, and any Spring Cloud Stream binder will work out of the box as a transport".
2) List existing starters: `spring-cloud-starter-bus-amqp`, `spring-cloud-starter-bus-kafka` but also `spring-cloud-gcp-starter-bus-pubsub` and any others that you know of.

I can send a PR for either option.

**Comment by spencergibb** [comment]
Option 1 please
