### ISSUE TITLE
spring-cloud-bus  integrated  github webhoot status is 404

### ISSUE THREAD

**Issue by Biubiuto** [spring-cloud/spring-cloud-bus#208]
I use bus to integrate my webhook, my address is "http://qg49ak.natappfree.cc/monitor", 
but when I check the details of my webhook is 404, I can't find the request path.
but I can submit a "/" via the curl command. 
The actuator /bus-refresh" request was successful.
I have changed the version to 2.0.7.RELEASE and Finchley.SR2
![image](https://user-images.githubusercontent.com/34942979/65408269-5ef15880-de17-11e9-806a-1c6768f3982d.png)

**Comment by spencergibb** [comment]
/monitor is part of spring cloud config. Finchley is no longer maintained. Please upgrade to Greenwich SR3 and try again

**Comment by Biubiuto** [comment]
As you said, I have changed the version to 2.1.7.RELEASE and Greenwich.SR3, but my interface address is still 404, my config-server console also does not print any logs, I see many versions on the web, The address of their interface is "/monitor" or "/bus/refresh", etc., can you give me a comment about what to fill in this specific address?

**Comment by spencergibb** [comment]
You've not provided any configuration or dependencies. Without it, I'd just be guessing
