### ISSUE TITLE
Spring Cloud Config client by Spring cloud bus cannot automatically refresh GitHub configuration

### ISSUE THREAD

**Issue by zhongxuebinwin8** [spring-cloud/spring-cloud-bus#209]
Spring Cloud Config client can't refresh the configuration dynamically. Config Server can refresh the configuration. I use Spring Cloud Config to do the unified configuration center, use Spring Cloud Bus to do configuration dynamic refresh, and dynamically refresh the configuration through GitHub Webhooks, using RabbitMQ to do message queue. The component version is as follows:
Spring Boot：2.1.8.RELEASE
Spring Cloud：Greenwich.SR3
Spring Cloud Config: 2.1.4.RELEASE
Spring Cloud Bus: 2.1.3.RELEASE
![image](https://user-images.githubusercontent.com/28047190/66553679-258e4c00-eb7e-11e9-86d3-8ee596b4cea3.png)
![image](https://user-images.githubusercontent.com/28047190/66553726-38088580-eb7e-11e9-9eb6-55a4519adebf.png)
![image](https://user-images.githubusercontent.com/28047190/66553740-3fc82a00-eb7e-11e9-9db9-e9d96ddbcc43.png)
The webhook request is successful, but the Config client does not refresh the configuration.
Config Server Configuration is as follows：
![image](https://user-images.githubusercontent.com/28047190/66555392-2c6a8e00-eb81-11e9-9c18-d90f93127c8b.png)
Config Server pom.xml:
![image](https://user-images.githubusercontent.com/28047190/66555093-abab9200-eb80-11e9-91fa-4c56ae4da1be.png)
Config Client properties
![image](https://user-images.githubusercontent.com/28047190/66555429-3e4c3100-eb81-11e9-8b08-1ecd8ef56e6e.png)
Config client pom.xml:
![image](https://user-images.githubusercontent.com/28047190/66555035-95053b00-eb80-11e9-89c8-08575d18f64d.png)

**Comment by zhongxuebinwin8** [comment]
https://github.com/spring-cloud/spring-cloud-bus/issues/124#issuecomment-441299536  solved

**Comment by smartinrub** [comment]
Hi, I think I'm facing the same issue, the webhook delivers successfully the request to the Spring Cloud Config Server application, however the refresh event created in RabbitMQ seems to be wrong and consumers are not getting the refresh event. 

I noticed it works fine for the `application.yml`, so I guess it's not able to retrieve the service name from the property file name. Is it now working for you? if so, could you please elaborate the solution?
