### ISSUE TITLE
Problem using org.springframework.cloud.stream.binder.rabbit.RabbitMessageChannelBinder to set up the subscribers on the Spring Cloud Bus

### ISSUE THREAD

**Issue by TabberGit** [spring-cloud/spring-cloud-bus#21]
I have a system with three components.  A ConfigServer, ServiceA, and ServiceB.  When they register against the Spring Cloud Bus, they all end up being tied as consumers to the same queue registered against the binder.springCloudBus queue.  This causes round-robining of messages, where only one service will actually be delivered a notification on the bus.

In `RabbitMessageChannelBinder.bindPubSubConsumer(String name, MessageChannel moduleInputChannel, Properties properties)`, it is not possible to give each queue a different name and have it bound to the same exchange.

    ConfigServer -----------------
                                 |
                        ------------------
    ServiceA ---------- | SpringCloudBus |
                        ------------------
                                 |
    ServiceB ---------------------

Exchange:  binder.topic.springCloudBus
Queue: binder.springCloudBus

The SINGLE queue ends up with three consumers.

This was discovered when we were working with the /refresh capabilities of spring-cloud.  In the scenario above, the refresh message is not passed to all necessary parties.

**Comment by spencergibb** [comment]
What does your configuration look like?

**Comment by TabberGit** [comment]
### ConfigServer


*bootstrap.yml*

    spring:
      application:
        name: configserver

*application.yml*

    server:
      port: 8888

    management:
      context-path: /admin

    spring:
      cloud:
        config:
          server:
            git:
              uri: ssh://git@stash.csgsystems.com:7999/~bout01/config-repo.git
              basedir: config-repo

### ServiceA

*bootstrap.yml*

    spring:
      application:
        name: serviceA
      profiles:
        active: development
      cloud:
        config:
          uri: http://localhost:8888

*application.yml*

    server:
      port: 8080

## ServiceB

*bootstrap.yml*

    spring:
      application:
        name: serviceB
      profiles:
        active: development
      cloud:
        config:
          uri: http://localhost:8888

*application.yml*

    server:
      port: 8081

**Comment by spencergibb** [comment]
Ok, what version are you using?

**Comment by TabberGit** [comment]
For spring-cloud-bus...1.1.0.BUILD-SNAPSHOT
For spring-cloud-stream-binder-rabbit...1.0.0.BUILD-SNAPSHOT

**Comment by hacbq** [comment]
same issues for me :(

**Comment by spencergibb** [comment]
I can verify this is happening.

**Comment by spencergibb** [comment]
@TabberGit @hacbq I've logged an issue with the spring-cloud-stream team and will await their feedback.

**Comment by spencergibb** [comment]
Tracking https://github.com/spring-cloud/spring-cloud-stream/issues/193 now

**Comment by hacbq** [comment]
I changed to release version :)

**Comment by TabberGit** [comment]
Pull request from @garyrussell - https://github.com/spring-cloud/spring-cloud-stream/pull/194 will resolve this...

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-stream/pull/194 has been closed and should be in SNAPSHOTS. I will verify that it fixes this problem.

**Comment by garyrussell** [comment]
@spencergibb `BindingProperties.group()` now [defaults to a random `UUID` (on master)](https://github.com/spring-cloud/spring-cloud-stream/pull/215) so this change could be backed-out at some point if you wish.
