### ISSUE TITLE
Migrate bus to the spring cloud function based messaging

### ISSUE THREAD

**Issue by marcingrzejszczak** [spring-cloud/spring-cloud-bus#215]
For Spring Cloud Bus >= 2.2.x

without this change Spring Cloud Bus will disable any functional configuration which means that a Stream application using Spring Cloud Stream's functional configuration will not work! If you're using the legacy (`@EnableBinding`) approach - everything will work fine.

**Comment by spencergibb** [comment]
duplicates #227
