### ISSUE TITLE
405 method not allowed for /actuator/bus-refresh

### ISSUE THREAD

**Issue by deepakThedeveloper** [spring-cloud/spring-cloud-bus#216]
I am trying to execute POST request on /actuator/bus-refresh url of spring-cloud and I am getting 405 as response status code with error message as Method Not Allowed.

**Below is my application.properties file of config server**
spring.application.name = config-server-service
server.port = 8012

spring.cloud.config.server.git.uri =*******
spring.cloud.config.server.git.username = *******
spring.cloud.config.server.git.password = *******
spring.cloud.config.server.git.clone-on-startup = true

management.endpoints.web.exposure.include = bus-refresh

spring.rabbitmq.host = localhost
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest

**Below dependencies are added in  pom.xml of config server**
  <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
  </dependency>

  <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-amqp</artifactId>
  </dependency>

Spring-boot-version that I am using is  2.2.4.RELEASE

![image](https://user-images.githubusercontent.com/43574533/73930916-65332d80-48fd-11ea-8a90-de0d6a056196.png)

**Comment by spencergibb** [comment]
What version? Are you trying to post a body?

**Comment by deepakThedeveloper** [comment]
spring cloud version? its 2.2.1 and actuator version is 2.2.4. Spring boot version is 2.2.4.
Nope I am not trying to post any body. I am just giving a post call to url http://localhost:8012/actuator/bus-refresh

**Comment by deepakThedeveloper** [comment]
Hello Sir, can you please provide any solution for this?

**Comment by sabahallah** [comment]
Hi, 

This is the same issue happened to me. I posted a question on stackoverflow [here](https://stackoverflow.com/questions/60861740/getting-method-not-allowed-error-when-post-actuator-bus-refresh-in-spring-clo). 

Please help if there's something wrong or any resolution.

Dependencies:

spring-cloud-config-server
spring-cloud-starter-bus-amqp
spring-boot-starter-actuator

Versions:
Boot: 2.2.5.RELEASE
Cloud: Hoxton.SR3

**Comment by asheCarry** [comment]
@spencergibb 
/bus-refresh does not support post. 
I can not beleive it.

**Comment by ChristinaDawoud** [comment]
I used the following dependency :

 <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-bus-amqp</artifactId>
instead of this :

<dependency>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-amqp</artifactId>
