### ISSUE TITLE
Unique Bus ID When Deployed To Kubernetes

### ISSUE THREAD

**Issue by ryanjbaxter** [spring-cloud/spring-cloud-bus#222]
When we deploy an app to Kubernetes we should try to come up with an ID to use that is unique to the container

**Comment by spencergibb** [comment]
See
https://github.com/spring-cloud/spring-cloud-bus/blob/2440fad1682039a291cd82c00c20551ebeef9746/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/BusEnvironmentPostProcessor.java#L51-L56

I wonder if we take this opportunity to move that to commons

**Comment by ryanjbaxter** [comment]
Probably a good idea to move to commons

**Comment by ryanjbaxter** [comment]
@spencergibb I was looking into this a bit....

1. After googling a bit I didn't see an obvious way to get a container id when running in a pod

2. I took a step back and thought if we just had a better way of generating a unique id (as opposed to it including a random number) it wouldn't really matter if we could access something like a container id in a pod

So I was poking around commons and found this code which is quite similar to what we have in bus already

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/commons/util/IdUtils.java#L37-L56

It uses `spring.application.instance_id` which we dont use in bus, could this possible solve the problem?  Would that id be the same after context refreshes?  I suppose I could just test it out, but wondering if you know off the top of your head.  I also just read in an old blog post that `spring.application.instance_id` would only be set when running in Cloud Foundry 😠

**Comment by spencergibb** [comment]
yeah, instance_id is gonna have the same problem.

My thought was a new random property source that, given a key, cached the random value.

`cloudrandom.app.long` would only ever generate 1 random long for the `app` key.

**Comment by ryanjbaxter** [comment]
This was implemented in https://github.com/spring-cloud/spring-cloud-commons/pull/719
