### ISSUE TITLE
spring-cloud-starter-bus-amqp

### ISSUE THREAD

**Issue by yzl1168** [spring-cloud/spring-cloud-bus#225]
Why do I get an error when I start this project after introducing spring-cloud-starter-bus-amqp：
Description:

Parameter 0 of method binderAwareRouterBeanPostProcessor in org.springframework.cloud.stream.config.BindingServiceConfiguration required a bean of type '[Lorg.springframework.integration.router.AbstractMappingMessageRouter;' that could not be found.

Action:

Consider defining a bean of type '[Lorg.springframework.integration.router.AbstractMappingMessageRouter;' in your configuration.

**Comment by spencergibb** [comment]
Please provide the versions you are using and the your build file

**Comment by yzl1168** [comment]
The version of springboot is  1.5.3.RELEASE ,and the version of springcloud  is Edgware.SR5

**Comment by spencergibb** [comment]
Those versions are no longer supported. Please upgrade to boot 2.2.6 and hoxton.sr3
