### ISSUE TITLE
Compatibility with spring cloud function

### ISSUE THREAD

**Issue by srinivasvsk** [spring-cloud/spring-cloud-bus#227]
**Is your feature request related to a problem? Please describe.**
Trying to start building kafka integration through spring cloud function which is not working, after some debugging it appears that spring cloud bus relies on @EnableBinding from cloud stream module. But the functional configuration in turn gets disabled if there is enablebinding in the context. So almost cant use both bus and functions in same context?

**Describe the solution you'd like**
Is there a plan for bus to support this

**Comment by spencergibb** [comment]
Yes we need to switch over

**Comment by spencergibb** [comment]
You can follow along at #236
