### ISSUE TITLE
AMQP binding error (Brixton.M3)

### ISSUE THREAD

**Issue by jjparsons** [spring-cloud/spring-cloud-bus#23]
I configured AMQP for centralized config and async communication between services. Considering moving over to Kafka for production. In the meantime this is blocking me. There seems to be a property binding error. See below.

POM Parent:

```
<parent>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-parent</artifactId>
<version>Brixton.M3</version>
</parent>
```

Rabbit Config:

```
@Configuration
@EnableRabbit
@Profile("!" + Profiles.CLOUD)
public class RabbitConfig {

}
```

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'spring.cloud.stream.binder.rabbit.default.CONFIGURATION_PROPERTIES': Could not bind properties to RabbitBinderConfigurationProperties (prefix=spring.cloud.stream.binder.rabbit.default, ignoreInvalidFields=false, ignoreUnknownFields=true, ignoreNestedProperties=false); nested exception is org.springframework.validation.BindException: org.springframework.boot.bind.RelaxedDataBinder$RelaxedBeanPropertyBindingResult: 4 errors

Field error in object 'spring.cloud.stream.binder.rabbit.default' on field 'requestHeaderPatterns': rejected value [STANDARD_REQUEST_HEADERS,*]; codes [typeMismatch.spring.cloud.stream.binder.rabbit.default.requestHeaderPatterns,typeMismatch.requestHeaderPatterns,typeMismatch.[Ljava.lang.String;,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.binder.rabbit.default.requestHeaderPatterns,requestHeaderPatterns]; arguments []; default message [requestHeaderPatterns]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.String[]' for property 'requestHeaderPatterns'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.String to type java.lang.String[]]

Field error in object 'spring.cloud.stream.binder.rabbit.default' on field 'defaultDeliveryMode': rejected value [PERSISTENT]; codes [typeMismatch.spring.cloud.stream.binder.rabbit.default.defaultDeliveryMode,typeMismatch.defaultDeliveryMode,typeMismatch.org.springframework.amqp.core.MessageDeliveryMode,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.binder.rabbit.default.defaultDeliveryMode,defaultDeliveryMode]; arguments []; default message [defaultDeliveryMode]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.amqp.core.MessageDeliveryMode' for property 'defaultDeliveryMode'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.String to type org.springframework.amqp.core.MessageDeliveryMode]

Field error in object 'spring.cloud.stream.binder.rabbit.default' on field 'acknowledgeMode': rejected value [AUTO]; codes [typeMismatch.spring.cloud.stream.binder.rabbit.default.acknowledgeMode,typeMismatch.acknowledgeMode,typeMismatch.org.springframework.amqp.core.AcknowledgeMode,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.binder.rabbit.default.acknowledgeMode,acknowledgeMode]; arguments []; default message [acknowledgeMode]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.amqp.core.AcknowledgeMode' for property 'acknowledgeMode'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.String to type org.springframework.amqp.core.AcknowledgeMode]

Field error in object 'spring.cloud.stream.binder.rabbit.default' on field 'replyHeaderPatterns': rejected value [STANDARD_REPLY_HEADERS,*]; codes [typeMismatch.spring.cloud.stream.binder.rabbit.default.replyHeaderPatterns,typeMismatch.replyHeaderPatterns,typeMismatch.[Ljava.lang.String;,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.binder.rabbit.default.replyHeaderPatterns,replyHeaderPatterns]; arguments []; default message [replyHeaderPatterns]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.String[]' for property 'replyHeaderPatterns'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.String to type java.lang.String[]]
```

**Comment by dsyer** [comment]
Is this a project using spring-cloud-bus? Do you have a simple sample to reproduce the issue?

**Comment by jjparsons** [comment]
Yes. Dependency is below. Would you mind if I simply added you to the project? It's only a beta at the moment...

```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-starter-bus-amqp</artifactId>
</dependency>
```

**Comment by dsyer** [comment]
Sure. Is it a private repo (if not you can just paste a link)?

**Comment by jjparsons** [comment]
Yes it is. One second..

**Comment by jjparsons** [comment]
Note, I'm using a super POM across all services. It's going well but this is the first blocking issue I have hit in a while... Feel free to shoot me a pull request if you like.

**Comment by dsyer** [comment]
Your parent pom is not as listed above (it's one that I can't download and can't build because I don't have access). Can you create a simple standalone sample project? Or give me the credentials for your repo?

**Comment by jjparsons** [comment]
Exactly but I send you the parent that my parent POM is currently using.

You have write permissions. If you want you could create a branch and stip out what you dont one. Or would you rather I do that for you?

**Comment by dsyer** [comment]
The problem is that the parent and 3 or 4 dependencies are not publicly available. I don't think I can work round that easily. If you sent me something by email I didn't get it yet, but if it was only the parent I doubt it will help.

**Comment by jjparsons** [comment]
Okay, will create a branch for you. One second.

**Comment by jjparsons** [comment]
Just sent you a pull request on a branch called `rabbit`.

**Comment by dsyer** [comment]
OK. So your app now starts up fine for me. How do I get to your error?

**Comment by jjparsons** [comment]
Well I would have to share multiple projects with you. Unless there is a way I can send you a few jars instead?

**Comment by dsyer** [comment]
I don't know. If this project works, what actually is the problem? If you can't distil it down to a simple sample, I doubt we are going to make a lot of progress. Sorry.

**Comment by jjparsons** [comment]
Note, this looks like a conversion issue on the spring.cloud.stream.binder.rabbit.default. I removed all of other things you saw in my parent POM and got it working.

Field error in object 'spring.cloud.stream.binder.rabbit.default' on field 'requestHeaderPatterns': rejected value [STANDARD_REQUEST_HEADERS,*]; codes [typeMismatch.spring.cloud.stream.binder.rabbit.default.requestHeaderPatterns,typeMismatch.requestHeaderPatterns,typeMismatch.[Ljava.lang.String;,typeMismatch]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [spring.cloud.stream.binder.rabbit.default.requestHeaderPatterns,requestHeaderPatterns]; arguments []; default message [requestHeaderPatterns]]; default message [Failed to convert property value of type 'java.lang.String' to required type 'java.lang.String[]' for property 'requestHeaderPatterns'; nested exception is org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type java.lang.String to type java.lang.String[]]

**Comment by dsyer** [comment]
So one of the things you removed to get it working must be changing the conversion service (or something)?

**Comment by jjparsons** [comment]
In each service I have been using a new instance of the GenericConversionService. Are you suggesting there is another instance I'm overriding or something? Usually the container would throw an exception if there was another instance already created as I wired my.

```
@Configuration
public class ConversionConfig {
	
	@Bean
	ConversionService conversionService() {
		final GenericConversionService conversionService = new GenericConversionService();
		conversionService.addConverter(new RoleDtoToRoleConverter());
		conversionService.addConverter(new RoleToRoleDtoConverter());
		conversionService.addConverter(new UserDtoToUserConverter(conversionService));
		conversionService.addConverter(new UserToUserDtoConverter(conversionService));
		return conversionService;
	}

}
```

**Comment by dsyer** [comment]
Yeah that's definitely it - you switched off one of the converters added by Spring Boot or Spring Cloud. The conversion service with bean name "conversionService" is special in the application context. I believe in a Spring Boot app you can create beans of type `Converter` to achieve your customization.

**Comment by jjparsons** [comment]
Okay, I will take a look at this. All of my converts implement `Converter`. The `GenericConversionService` interface is the only one that includes the `addConverter(...)` method. Can I configure all of my converts using DI via `@Component`?

**Comment by jjparsons** [comment]
The solution was to rename the converter:
```
@Bean
	ConversionService dtoConversionService() {
		final GenericConversionService dtoConversionService = new GenericConversionService();
		dtoConversionService.addConverter(new RoleDtoToRoleConverter());
		dtoConversionService.addConverter(new RoleToRoleDtoConverter());
		dtoConversionService.addConverter(new UserDtoToUserConverter(dtoConversionService));
		dtoConversionService.addConverter(new UserToUserDtoConverter(dtoConversionService));
		return dtoConversionService;
	}
```

Note, other services include the following which was no evident:

* mvcConversionService
* integrationConversionService
