### ISSUE TITLE
update profile. config client not working

### ISSUE THREAD

**Issue by AsiaMa** [spring-cloud/spring-cloud-bus#230]
When i update order.yml, config client is working(can auto refresh). While update order-dev.yml or order-test.yml, config client is not working(can't auto refresh). This is look like config-client only listening order.yml update。
spring-boot-starter  :  2.1.15.RELEASE
spring-cloud  :   Greenwich.SR6

sample:
  if i update order.yml , it is working
![image](https://user-images.githubusercontent.com/22593341/87093047-22400200-c26f-11ea-8afe-975acb41cbaa.png)
![image](https://user-images.githubusercontent.com/22593341/87093133-469bde80-c26f-11ea-9e17-b700426bbf10.png)
my config-client  can recieve messge:
![image](https://user-images.githubusercontent.com/22593341/87093277-86fb5c80-c26f-11ea-9e1d-5df3442db49a.png)
but if i only update order-dev.yml or order-test.yml, my config-client can't recieve message. the console nothing
![image](https://user-images.githubusercontent.com/22593341/87093584-00934a80-c270-11ea-8eb5-6e244bac103b.png)
it my order-dev.yml 
![image](https://user-images.githubusercontent.com/22593341/87093626-156fde00-c270-11ea-852f-0f73c9709b2d.png)
it my order-test.yml
![image](https://user-images.githubusercontent.com/22593341/87093694-2fa9bc00-c270-11ea-812c-f9c84886b85d.png)
when i update girl.age in order-dev.yml or order-test.yml, it not working. only update order.yml, it is working（config-client can recieve message）. how i solve it problem?

**Comment by AsiaMa** [comment]
it's my config-client bootstrap.yml
![image](https://user-images.githubusercontent.com/22593341/87094067-d2fad100-c270-11ea-8e79-cd16b785d36d.png)
and it's my dependencies
![image](https://user-images.githubusercontent.com/22593341/87094249-28cf7900-c271-11ea-9a90-c42f8306b416.png)

**Comment by AsiaMa** [comment]
it's my bootstrap.yml
![image](https://user-images.githubusercontent.com/22593341/87094397-692ef700-c271-11ea-8b63-a032e9e41378.png)
and it's my dependencies
![image](https://user-images.githubusercontent.com/22593341/87094441-7ba93080-c271-11ea-93be-27dbbed54ab3.png)

**Comment by AsiaMa** [comment]
it's my config-server bootstrap.yml
![image](https://user-images.githubusercontent.com/22593341/87098497-0130de80-c27a-11ea-8083-fef6f38fc20c.png)
it's my config-server dependencies
![image](https://user-images.githubusercontent.com/22593341/87098533-1ad22600-c27a-11ea-9d91-bca392cd34f9.png)

**Comment by AsiaMa** [comment]
it's my BoyConfig
![image](https://user-images.githubusercontent.com/22593341/87154600-19d9dc80-c2ec-11ea-93ff-405fa8159732.png)

**Comment by AsiaMa** [comment]
when i debug source code, i fount getDefaultServiceId(ConfigurableEnvironment environment)  not return correct serviceId
,so i change to the following solve this problem.
![image](https://user-images.githubusercontent.com/22593341/87228813-3b16f780-c3d6-11ea-9 6da-10d84675dc3a.png)
I don't know if I should do it, but it does solve the problem.

**Comment by spencergibb** [comment]
This is the right thing to do in Greenwich and it has already been updated in Hoxton.

**Comment by AsiaMa** [comment]
> This is the right thing to do in Greenwich and it has already been updated in Hoxton.

Thank you.
