### ISSUE TITLE
User-defined binding properties for springCloudBusOutput take not effect

### ISSUE THREAD

**Issue by JordiMartinezVicent** [spring-cloud/spring-cloud-bus#244]
spring-cloud-bus version: 3.0.0

When a message is sent through the bus, the binding properties defined with the namespace 'spring.cloud.stream.bindings.springCloudBusOutput' take no effect.

It is due to the StreamBridegBus is doing the following: 
```
public void send(RemoteApplicationEvent event) {
	// TODO: configurable mimetype?
	this.streamBridge.send(properties.getDestination(), MessageBuilder.withPayload(event).build());
}
```

But it should do this instead: 
```
public void send(RemoteApplicationEvent event) {
	// TODO: configurable mimetype?
	this.streamBridge.send(BusConstants.OUTPUT, MessageBuilder.withPayload(event).build());
}
```

As StreamBridegBus is using the destination instead of the bindingName, spring-cloud-stream is not able to map the binding properties (i.e spring.cloud.stream.bindings.springCloudStream.producer.header-mode.embeddedheaders). 

Note that if the change is done, the following property should be set: 

`--spring.cloud.stream.bindings. springCloudBusOutput.destination: ${spring.cloud.bus.destination}`

maybe at BusEnvironmentPostProcessor?

Please, refer to https://github.com/spring-cloud/spring-cloud-stream/issues/2077#issuecomment-759518661 

Many thanks in advance to take a look at this

**Comment by JordiMartinezVicent** [comment]
@spencergibb if you agree, I am happy to make a pull request

**Comment by spencergibb** [comment]
PRs welcome
