### ISSUE TITLE
TraceListener does not appear to add anything to the HttpTraceRepository

### ISSUE THREAD

**Issue by celdridge91190** [spring-cloud/spring-cloud-bus#251]
It looks like in the latest commit, TraceListener no longer adds the event information to the HttpTraceRepository so the functionality to trace events and acknowledgements no longer works. It looks like a comment was added for it to be fixed as the call to the repository was commented out. 

https://github.com/spring-cloud/spring-cloud-bus/blob/f98518e15a474490e4c9a54375c347672a316e3c/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/event/TraceListener.java#L47

**Comment by spencergibb** [comment]
indeed, this isn't an http trace. Duplicates #193
