### ISSUE TITLE
Support HTTP requests instead of Kafka / AMPQ

### ISSUE THREAD

**Issue by code-magician323** [spring-cloud/spring-cloud-bus#264]
**Is your feature request related to a problem? Please describe.**
I want to send events from `spring-cloud-config` with `spring-cloud-monitor`, through HTTP, instead of AMPQ / Kafka.

**Describe the solution you'd like**
Creation of some `spring-cloud-bus-webflux` / `spring-cloud-bus-web`.

**Comment by ryanjbaxter** [comment]
To accomplish what exactly?

**Comment by ryanjbaxter** [comment]
Closing in favor of https://github.com/spring-cloud/spring-cloud-config/issues/2152
