### ISSUE TITLE
Unnecessary BusConfiguration Class Creation in RemoteApplicationEvent Usage

### ISSUE THREAD

**Issue by iamvishalparekh** [spring-cloud/spring-cloud-bus#274]
**Describe the bug**
In the context of using RemoteApplicationEvent in our Spring Boot project, the current documentation suggests creating a new BusConfiguration class to register and deserialize the event. However, this separate class creation may not be necessary if there are no specific configurations to be made.

Instead, the @RemoteApplicationEventScan annotation can be applied directly to the Application class where the main method resides.

**Sample**

**Current documentation says :**

You can register that event with the deserializer in the following way:

[source,java]
```
package com.acme;

@Configuration
@RemoteApplicationEventScan
public class BusConfiguration {
    ...
}
```

[source,java]
```
package com.acme;

@Configuration
//@RemoteApplicationEventScan({"com.acme", "foo.bar"})
//@RemoteApplicationEventScan(basePackages = {"com.acme", "foo.bar", "fizz.buzz"})
@RemoteApplicationEventScan(basePackageClasses = BusConfiguration.class)
public class BusConfiguration {
    ...
}
```

**Instead we can also do below configuration and save creating above class.**

```
package com.acme;

@SpringBootApplication
@RemoteApplicationEventScan
public class Application {
          public static void main(String[] args) {
               SpringApplication.run(Application.class, args);
         }
}
```
This approach is more streamlined and eliminates the need for an additional class.

**Comment by ryanjbaxter** [comment]
I agree that this would also work, but I think I prefer the way the current documentation is written because it applies this will work on any `@Configuration` class which would include a class annotated with `@SpringBootApplication`.  I think if we just showed an example using `@SpringBootApplication` someone might interpret that as it has to only go on that class.
