### ISSUE TITLE
1.1.0.RC1 not published in repo.spring.io

### ISSUE THREAD

**Issue by cforce** [spring-cloud/spring-cloud-bus#32]
<spring-cloud-bus.version>1.1.0.RC1</spring-cloud-bus.version> is referenced in spring cloud brixton rc1 release deps, but not resolvable in repo https://repo.spring.io/

**Comment by mbogoevici** [comment]
Hi,

The proper repository url for the artifact is:

http://repo.spring.io/libs-milestone

Cheers,
Marius

**Comment by spencergibb** [comment]
From his gitter comments, I think he's complaining about the bus redis starter specifically.

**Comment by cforce** [comment]
see also https://github.com/spring-cloud/spring-cloud-stream/issues/454 and https://github.com/spring-cloud/spring-cloud-starters/issues/47

**Comment by spencergibb** [comment]
closing, point to the right repo and `spring-cloud-starter-bus-redis` is no longer provided.
