### ISSUE TITLE
Publish updated documentation

### ISSUE THREAD

**Issue by bitsofinfo** [spring-cloud/spring-cloud-bus#36]
Whats the ETA for Kafka support? in an official release?

**Comment by spencergibb** [comment]
It's officially supported since May 11 https://spring.io/blog/2016/05/11/spring-cloud-brixton-release-is-available

**Comment by bitsofinfo** [comment]
Then you guys should update the docs

```.....The only implementation currently is with an AMQP broker as the transport, but the same basic feature set (and some more depending on the transport) is on the roadmap for other transports.```

**Comment by bitsofinfo** [comment]
thx

**Comment by spencergibb** [comment]
The [docs](https://github.com/spring-cloud/spring-cloud-bus/blob/master/docs/src/main/asciidoc/spring-cloud-bus.adoc#customizing-the-message-broker) have already been updated, they just need to be published. http://cloud.spring.io/spring-cloud-static/spring-cloud.html

**Comment by spencergibb** [comment]
@dsyer looks like the bus docs haven't been published in a while.

**Comment by dsyer** [comment]
Marcin just added a new build step. I think they are up to date now (or they will be when all the builds are green).
