### ISSUE TITLE
Events targeted at an application with a profile but no id should go to all instances

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-bus#38]
We already translate a plain destination with no qualifier by adding `:**` (matching all). But we don't extend the same courtesy to `foo:bar` (matching also `foo:bar:*` for instance). This causes issues in the config server monitor (https://github.com/spring-cloud/spring-cloud-config/issues/436).

**Comment by yidongnan** [comment]
I see 1.1.1.RELEASE tag include it.
But in maven repo and spring repo, 1.1.1.RELEASE not include it.
https://repo.spring.io/webapp/#/artifacts/browse//search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5Ijoic3ByaW5nLWNsb3VkLWJ1cy0xLjEuMS5SRUxFQVNFIiwic2VsZWN0ZWRSZXBvc2l0b3JpZXMiOltdfQ==

http://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-bus/1.1.1.RELEASE

**Comment by spencergibb** [comment]
@yidongnan What do you mean by 
> 1.1.1.RELEASE not include it.

**Comment by yidongnan** [comment]
@spencergibb Yes.May be don't deploy to maven center repo

**Comment by spencergibb** [comment]
It certainly is http://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-bus/

**Comment by yidongnan** [comment]
@spencergibb 
![image](https://cloud.githubusercontent.com/assets/3163314/18771113/c7594760-816e-11e6-904c-0124bfc0b8d3.png)
I decompile this jar.
It not newest code with 1.1.1.RELEASE
https://github.com/spring-cloud/spring-cloud-bus/blob/v1.1.1.RELEASE/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/event/RemoteApplicationEvent.java#L35

**Comment by spencergibb** [comment]
@yidongnan opened #42
