### ISSUE TITLE
Bus 1.1.1.RELEASE is missing code

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-bus#42]
From https://github.com/spring-cloud/spring-cloud-bus/issues/38#issuecomment-249075789

e3dd8b450c5d2cd099966334c4395fbebbcdf15d should be in http://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-bus/1.1.1.RELEASE/spring-cloud-bus-1.1.1.RELEASE.jar but it is not.

A new release should do the trick.

/cc @dsyer

**Comment by dsyer** [comment]
Fixed in 9cd763a0 (and pushed 1.1.2 to Maven repos).
