### ISSUE TITLE
Applications specifying `server.port` do not receive refresh events

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-bus#43]
Can be reproduced with https://github.com/mstine/fortune-teller, following the steps in  https://github.com/mstine/fortune-teller#testing-refresh (the `ngrok` part is not required though, relying on the refresh of a local git repository should suffice). 

See https://github.com/spring-cloud/spring-cloud-bus/blob/master/spring-cloud-bus/src/main/java/org/springframework/cloud/bus/ServiceMatcher.java#L31.  

The underlying cause is that the `destinationService` supplied by the event does not take into account the fact that the `serviceId` may include port information for applications that specify `server.port` explicitly.  For the example above, when `destinationService` is `*`, it doesn't match `ui:8081`, which is the contextId of the `fortune-teller-ui` application.

**Comment by mbogoevici** [comment]
Actually, this seems to be specific to the `*` wildcard. We should probably use `**` instead if the intent is to indicate global broadcast.

**Comment by spencergibb** [comment]
#38 is a recent change.

**Comment by mbogoevici** [comment]
Yeah, it seems to have changed the semantics of '*' - previously it was equivalent to '*:**'. This has made the treatment of wildcards more restrictive, as for example now anything that contains a wildcard is handled differently - previously things like "foo*" were also suffixed with ':**'. Not sure if this was intentional.

**Comment by mstine** [comment]
Timeline of a SR that will contain this fix? Thanks.

**Comment by spencergibb** [comment]
Hopefully soon (this week?)
