### ISSUE TITLE
is JMS supported in addition to Kafka/RabbitMQ?

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-bus#45]
My company unfortunately never adopted AMQP-based messaging systems and I'm stuck with JMS... Is there a way to use it to propagate the /monitor changes of Github Enterprise changes?

If not, is there a direction I could take to implement that?

**Comment by mbogoevici** [comment]
@marcellodesales Generally Spring Cloud Bus supports a messaging system to the extent that a Spring Cloud Stream binder exists for it. The Spring Cloud Stream Binder for JMS is in incubation here: https://github.com/spring-cloud/spring-cloud-stream-binder-jms. 

Do note that JMS support requires clients and adapters specific to your messaging system. What messaging system are you using currently ?

**Comment by marcellodesales** [comment]
Thanks @mbogoevici for the info and it is exciting to know you guys have the initial version in incubation. I would like to provide feedback while helping us get through this support.

Yeah, so we have a centralized ActiveMQ, older versions I would consider, as our Messaging system where:

1. Our team need to onboard
2. Our team does not maintain nor have direct access to it

Where should I start looking at in your project? Sample code?

**Comment by raffian** [comment]
ActiveMQ supports AMQP 1.0, can it be used as a backing implementation for spring cloud bus broker?

**Comment by spencergibb** [comment]
I have no idea if activemq is compatible with the stream amqp binder. @mbogoevici ?

**Comment by raffian** [comment]
@spencergibb @mbogoevici  
Found this, ActiveMQ stream binder implementation, assuming it works it should meet our need.
https://github.com/spring-cloud/spring-cloud-stream-binder-jms/tree/master/spring-cloud-stream-binder-jms-activemq
