### ISSUE TITLE
Github Webhook, RefreshRemoteApplicationEvents, on Load-balanced Config Servers

### ISSUE THREAD

**Issue by marcellodesales** [spring-cloud/spring-cloud-bus#47]
Setup
=====
We have load-balanced our Config Servers to support multiple teams across our organization. That way, we have a centralized Configuration Service that uses the Multi-git repos support where services need to onboard and specify their Github Enterprise Org/Repo path and app name. So, when dealing with `config-server.mycompany.net:8888`, the app services can be talking to any of the config servers. 

Question
======

* Question for @spencergibb, based on https://spencer.gibb.us/blog/2015/09/24/spring-cloud-config-push-notifications/, is there a way to use the same strategy of using the Github Webhook and the Cloud Bus to distribute the message Webhook Event to all Config Servers?

* What are the consequences of using the Bus for this scenario, given that all Config servers will try to send Push Notification to all the client apps using the `RefreshRemoteApplicationEvents` (delivered through Spring Cloud Bus with RabbitMQ or other transport)?

thanks a lot for any help!

**Comment by spencergibb** [comment]
@marcellodesales why do you need the webhook to go to each server? It would be bad for each server to receive each webhook.

**Comment by marcellodesales** [comment]
@spencergibb They don't need to go to each server. I was thinking:

* A single entity receives the Webhook Event.
* Communicates to ALL Config Servers and synchronizes
* When All config servers are updated, then a fanout message to all Clients are sent using `RefreshRemoteApplicationEvents`.

Maybe we could use the https://cloud.spring.io/spring-cloud-dataflow/? Any suggestion?

**Comment by spencergibb** [comment]
Config servers don't get updated until a client asks. Again, I don't see the need for the webhook or a resulting message to go to each config server.

**Comment by marcellodesales** [comment]
Hey @spencergibb .. Thanks for the notes... But I think Spring Cloud Bus is used to propagate the changes on a config repo to the config server and, thus, avoiding applications checking for updates. 

Anyway, let me try to expand on the potential `race condition` problem when having a Load-balanced Config Server using the Spring Cloud Bus. This is based on my current understand of the module so far.

(1) Single Config Server <-> Multiple Apps
====

* Config server `config-server:8888` is the shared config server for ALL applications
* Clients making changes to a shared property in `application.properties` from the same exact `config repo`, propagates to all applications
* Using Spring Cloud Bus AMQP we can use the `/monitor` endpoint setup as a `Webhook` to the `config repo`.
* http://zoltanaltfatter.com/2016/06/30/centralized-configuration-with-spring-cloud-config/ makes a very good description of what I'm referring to and uses some of the concepts you described at https://spencer.gibb.us/blog/2015/09/24/spring-cloud-config-push-notifications/
* A single config server is involved in the change. All client applications reach to the single Config Server `config-server:8888`.
 * At this point, the config server is "`refreshed`" with the new changes, and all the application clients will receive the `/refresh` call based on the `/monitor` message. Since all applications are pointing to the same exact config server, there's no race condition here (N apps -> 1 Config server)

(2) Miltiple Config Server <-> Multiple Apps
====

* Config server `config-server:9999` is a Load-Balanced VIP
 * `config-server:9991`, `config-server:9992`, `config-server:9993`...
 * Applications are setup to use the `spring.cloud.config.uri=config-server:9999`, and thus, receiving config updates from ANY of the servers in the Load-Balanced pool.

When making changes to properties:

* The same Spring Cloud Bus AMQP is desired to be used with the `/monitor` endpoint setup as a `Webhook` to the `config repo`.
 * The URL used on the Webhook is `config-server:9999/monitor`, which can hit any of the servers in the Load-balancing pool `config-server:9991`, `config-server:9992`, `config-server:9993`...

With this scenario, the first config-server in the pool, say `config-server:9992`:

* The server receives the message and notify AMQP server of the changes.
* All applications are informed about the change just like scenario `(1)`. 
* A potential race condition can occur when an application, configured with `config-server:9999/monitor`, fetches updates based on the AMQP message received, when the load balancer offers `config-server:9993`.
 * Since `config-server:9993` hasn't updated yet, the new changes are reflected.

I hope I have made this more clear...

**Comment by spencergibb** [comment]
You misunderstand.
> But I think Spring Cloud Bus is used to propagate the changes on a config repo to the config server and, thus, avoiding applications checking for updates.

It does not do this. All it does is tell config clients that a change has occurred at which point they will query config server, which, in turn, will pull from git. There is no race condition, config server instances are stateless.

**Comment by marcellodesales** [comment]
Sounds good Spencer.. thanks for clarifying it...
