### ISSUE TITLE
Expose BusMvcEndpoint Operations via JMX

### ISSUE THREAD

**Issue by steve-oakey** [spring-cloud/spring-cloud-bus#50]
It would be beneficial to have the BusMvcEndpoint operations exposed to JMX. We use the Spring Boot Admin dashboard which gives very easy access to JMX operations via Jolokia. In this case it is much easier for administrators to access these operations rather than POST'ing to the specific endpoints.

Willing to contribute if this is a welcome contribution. I have already done this for some custom BusMvcEndpoint's for custom `RemoteApplicationEvent`'s in our projects.

**Comment by spencergibb** [comment]
PR would be welcome

**Comment by steve-oakey** [comment]
Just to let you guys know I haven't forgotten about this. Will probably get some time over the holiday break to get this done.
