### ISSUE TITLE
RefreshListener doesn't respect destination service

### ISSUE THREAD

**Issue by JWThewes** [spring-cloud/spring-cloud-bus#56]
When a service is receiving a RemoteApplicationRefreshEvent the destinationServiceId isn't checked. Every application does refresh it's context. Would be great to only refresh the applications that match the given destinationServiceId.

Or is the current behaviour correct?

**Comment by spencergibb** [comment]
No, can you provide more information besides it doesn't work? Versions? Steps to reproduce?

**Comment by JWThewes** [comment]
Well I think I've been wrong here. I've been observing the ConfigServer itself. It has always been reloading it's Environment no matter what I put in the /monitor call.
I think this is reasonable.

The other services using the ConfigServer only get messages which contain their application name.
So I think the behaviour is correct.
My mind was just full yesterday.
Sorry.

BTW I'm on Cameden.SR5

So as long as you agree that it is ok for the config server to refresh no matter what the path contains we can close this one.

**Comment by spencergibb** [comment]
The service that recieves the refresh event will act on the event regardless of who it was for. So, sounds like everything is OK.
