### ISSUE TITLE
Spring Cloud Bus broken with Camden.SR5 and spring boot 1.5.1 on Windows

### ISSUE THREAD

**Issue by Rico010** [spring-cloud/spring-cloud-bus#59]
I had a project with Camden.SR4 and spring boot 1.4.3. Spring Cloud Bus worked fine, however after incrementing version to Camden.SR5 and spring boot 1.5.1 POSTing to /bus/refresh will not refresh other services (only the service on which /bus/refresh is called is refreshed).

**Comment by spencergibb** [comment]
Duplicate of #55?

**Comment by Rico010** [comment]
Hi Spencer,

Thank you for the hint on #55

However, I've retested everything. The issue is that Cloud Bus always works on MacOS X. With both 1.5.1 + Camden.SR5 and 1.4.3 + Camden.SR4. The issue is that it does not work on Windows 7. May be it is related to my particular Windows, I am not sure though. Do not have a second Windows PC to check :)

On Windows both 1.5.1 + Camden.SR5 and 1.4.3 + Camden.SR4 Clid Bus does not propagate refresh events to services.

**Comment by Rico010** [comment]
By the way, Cloud Stream works fine. The issue is related to Cloud Bus

**Comment by spencergibb** [comment]
There was an issue upstream in [spring cloud stream](https://github.com/spring-cloud/spring-cloud-stream/issues/810) which caused a problem in bus (but not generic stream). Can you try with snapshots?

**Comment by Rico010** [comment]
I have retested everything with latest releases of Boot - 1.5.2 and Cloud - Camden.SR6.
Everything works fine now. Bugs are fixed with these releases.
Thank you!
