### ISSUE TITLE
/bus/refresh not work in Camden.SR5

### ISSUE THREAD

**Issue by TonyLiu0112** [spring-cloud/spring-cloud-bus#60]
Hi, When I used the endpoints of /bus/refresh/ to refresh configuration on multiple instances(with rabbitmq), It does not work on Camden.SR5, I try the same code with Camden.SR4 and Camden.SR6, it works.

when I used Camden.SR5, I saw the rabbitmq created two exchanges: 
**springCloudBusInput**
**springCloudBusOutput**

but when SR4 and SR6, it created one exchange only : **springCloudBus**

I see the [Document](http://cloud.spring.io/spring-cloud-static/Camden.SR5/#_push_notifications_and_spring_cloud_bus) did not find anything.

I see the code of class: org.springframework.cloud.bus.BusAutoConfiguration, the init method always gets the default destination for "springCloudBus".

Is there some bug in Camden.SR5?

**Comment by spencergibb** [comment]
Yes there was a bug and it is fixed in Camden.SR6 https://spring.io/blog/2017/03/10/spring-cloud-camden-sr6-is-available
