### ISSUE TITLE
EnvironmentChangeListener not handle EnvironmentChangeRemoteApplicationEvent

### ISSUE THREAD

**Issue by sunnyWangXin** [spring-cloud/spring-cloud-bus#61]
Hi, I send an EnvironmentChangeRemoteApplicationEvent to Kafka, and saw the event received by consumer (through @EnableBinding(Sink.class) and @StreamListener(Sink.INPUT)) . But it didn't handle by EnvironmentChangeListener automatically. 
In my mind, the listener should be setup if spring.cloud.bus.env.enabled=true and handle environment event that received. Is any other configuration I need add if I want to use the listener? Like some annotation? definition? Thanks

**Comment by spencergibb** [comment]
No. Can you provide us with more information? Versions? Dependencies?

**Comment by sunnyWangXin** [comment]
Oh, sorry I found my configuration for Kafka not work well, thanks for your response @spencergibb
