### ISSUE TITLE
Spring Cloud Consul Home Page - Incorrect GA Version & Broken Documentation Link

### ISSUE THREAD

**Issue by yohanliyanage** [spring-cloud/spring-cloud-bus#67]
Spring Cloud Consul Home https://cloud.spring.io/spring-cloud-consul/ lists the current GA version as 1.3.0 although the latest release is 1.2.0. With this, the Reference documentation link points to http://cloud.spring.io/spring-cloud-static/spring-cloud-consul/1.3.0.RELEASE/ which is a dead link.

**Comment by spencergibb** [comment]
Thanks, fixed.
