### ISSUE TITLE
RefreshRemoteApplicationEvent is processed locally even if not intended

### ISSUE THREAD

**Issue by dsyer** [spring-cloud/spring-cloud-bus#68]
`RefreshRemoteApplicationEvent` (and probably all remote events) are handled locally by the application listeners in the context. That means if you publish one, intended to reach another service, it will be processed locally as well as remotely. In some cases that is harmless, but it seems like a bug to me.

**Comment by spencergibb** [comment]
2.0 might be a good time to rework this.

**Comment by sunnyWangXin** [comment]
Hi, do we have any workaround now? Something like close local event listener? or add message filter? Cause I used EnvironmentChangeRemoteApplicationEvent, it will set received properties into environment directly which really hurt project.....

**Comment by spencergibb** [comment]
@sunnyWangXin no

**Comment by rafaelrddc** [comment]
Good Morning!

Wouldn't it be a solution in class '**BusAutoConfiguration**' in method '**acceptLocal**' to take into account field '**destinationService**'?

If this is a valid solution I can perform and request the pull request.

**Comment by rafaelrddc** [comment]
@spencergibb @dsyer I have a suggestion to correct this behavior, if you accept already make the changes and request the pull request.

Create class RemoteApplicationListener

```
public abstract class RemoteApplicationListener extends ApplicationListener<E extends RemoteApplicationEvent>  {
       
      private final ServiceMatcher serviceMatcher;
      
      public RemoteApplicationListener(ServiceMatcher serviceMatcher) {
             this.serviceMatcher = serviceMatcher;
      }

      @Override
      public void onApplicationEvent(E event) { 
             if (this.serviceMatcher.isForSelf(event)) {
                    this.processApplicationEvent(event);         
             }
      }

      public abstract void processApplicationEvent(E event);
}
```

Then we take all the classes that listen for events and put them to extend this new class.

What do you think?

**Comment by spencergibb** [comment]
PRs welcom

**Comment by rafaelrddc** [comment]
Show, I will make the changes and request the PR.

I make this change from which branch?

**Comment by spencergibb** [comment]
I'd use 2.1.x and we can merge forward.
