### ISSUE TITLE
Spring 5.x fails to to map RefreshRemoteApplicationEvent kafka message events

### ISSUE THREAD

**Issue by vbasem** [spring-cloud/spring-cloud-bus#70]
I am currently testing the config server from branch 2.x with spring cloud bus on the 2.x branch as well
```gf
    compile('org.springframework.cloud:spring-cloud-starter-config:2.0.0.BUILD-SNAPSHOT')
    compile('org.springframework.cloud:spring-cloud-starter-bus-kafka:2.0.0.BUILD-SNAPSHOT')
```

Config server produces the event RefreshRemoteApplicationEvent which then throws an exception in the class MappingJackson2MessageConverter due to the fact that there are no subtypes of the class RemoteApplicationEvent.

We currently hacked around the problem by registering the subtypes, but I am guessing this could be done in source:

```java
    
    @Autowired
    private CompositeMessageConverter compositeMessageConverter;
    
    @PostConstruct
    public void init() {
        for (MessageConverter messageConverter : this.compositeMessageConverter.getConverters()) {
            if (messageConverter instanceof MappingJackson2MessageConverter) {
                ((MappingJackson2MessageConverter)messageConverter).setObjectMapper(getObjectMapper());
                break;
            }
        }
    }

    protected ObjectMapper getObjectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(MapperFeature.DEFAULT_VIEW_INCLUSION, false);
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        objectMapper.registerSubtypes(RefreshRemoteApplicationEvent.class, AckRemoteApplicationEvent.class);
        return objectMapper;
    }
```

Am I doing something wrong, or this is the way to go ?

Thanks.

**Comment by spencergibb** [comment]
I'd say not. It maybe that there are issues on 2.0.x

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
