### ISSUE TITLE
Why not update the config automatically through the listener?

### ISSUE THREAD

**Issue by xjtushilei** [spring-cloud/spring-cloud-bus#71]
Why not update the config automatically through the listener? so that we don't need the webhooks in github.

Of course, we can turn the bus module into other modules, such as checking whether the configuration file is updated, then finding out the change, and then updating only the changed part.

**Comment by spencergibb** [comment]
What would we "listen" for?

**Comment by xjtushilei** [comment]
Thank you for your answer. I'm sorry my statement may be wrong. I just want to say that updating through bus is not smart enough. I want to use the configuration center more intelligently. But it suddenly occurred to me that the basic functions can be achieved, but **we need to configure what to update** ，or maybe I don't know how to do it. I hope that in the future for users to do more, more convenient. He can find updates by himself and change some values automatically through webhook.That is amazing
.

I hope spring cloud is getting better and better

**Comment by spencergibb** [comment]
I'm afraid I still don't understand. Can you describe specifically what you are trying to achieve?

**Comment by xjtushilei** [comment]
Maybe I need to learn more about Cloud Bus
