### ISSUE TITLE
Increase independence of bus clients

### ISSUE THREAD

**Issue by ama-patrick** [spring-cloud/spring-cloud-bus#74]
Hi,
I was evaluating Spring Cloud Bus as event bus between our microservices using the 1.3.1.RELEASE version. During the evaluation I was facing two issues. I simply quickfixed those issues for me, without knowing the impact or caring about perfomance/style, this is why I did not create a PR.

1. No library containing all events available is shared between the applications to ensure the independence of the services. So every application implements the event classes it depends on and so not all events possible are available as bean implementation. Those events are reflected using the `org.springframework.cloud.bus.event.UnknownRemoteApplicationEvent`.  
Unfortunately this one initializes the **originService** with null, which causes a NullPointerException at `org.springframework.util.AntPathMatcher.doMatch(AntPathMatcher.java:191)` during service evaluation. Therefore I patched it to simply initialize with an empty String - works, but...well.

```java
public class UnknownRemoteApplicationEvent extends RemoteApplicationEvent {

  /* ... */

  public UnknownRemoteApplicationEvent(final Object source, final String typeInfo, final byte[] payload) {
    super(source, "" /* Modified */, null);
    this.typeInfo = typeInfo;
    this.payload = payload;
  }

  /* ... */
}
```

2. The events' package name may vary from service to service. This is ok for the actual events, which will be resolved by the bean name. The resulting ack however will send the fq classname of the event bean as *event* property, which will cause all listeners to fail, as they are trying the resolve the class but the fq classname is unknown to other applications.  
This one was a little bit more tricky, as the event field is set via reflection. So I had to change the type of the *event* property to String, introduced a field for the actual type of the event and evaluated the class in the `getEvent()` method to keep everything running. As fallback for unknown classes I used the `UnknownRemoteApplicationEvent`.

```java
public class AckRemoteApplicationEvent extends RemoteApplicationEvent {

  /* ... */

  private final String event; // Modified so a String will be set instead of a Class
  private Class<? extends RemoteApplicationEvent> eventType; // Added to store the type

  /* ... */
  
  public AckRemoteApplicationEvent(final Object source, final String originService,
      final String destinationService, final String ackDestinationService, final String ackId,
      final Class<? extends RemoteApplicationEvent> type) {
    super(source, originService, destinationService);
    this.ackDestinationService = ackDestinationService;
    this.ackId = ackId;
    this.event = type.getName(); // Modified
    this.eventType = type; // Added
  }

  /* ... */

  // Modified
  public Class<? extends RemoteApplicationEvent> getEvent() {
    if (this.eventType == null) {
      try {
        this.eventType = (Class<? extends RemoteApplicationEvent>) Class.forName(event);
      } catch (ClassNotFoundException e) {
        this.eventType = UnknownRemoteApplicationEvent.class;
      }
    }
    return this.eventType;
  }

  /* ... */

}
```

I am looking forward for your feedback. Maybe I am trying to do something the Spring Cloud Bus was not meant for or I could have solved my issues easier. Otherwise we would be happy if you could adapt those changes, so we could use an unpatched version of the project.

Cheers
Patrick

Edit: You will also find the diff here: https://github.com/ama-patrick/spring-cloud-bus/commit/3f512312b171bb2bfdbbffa1523d4b07e1f1bffb

**Comment by spencergibb** [comment]
I think a PR would be nice. Maybe a bit of documentation on how it works too.

**Comment by ama-patrick** [comment]
Sure, documentation in terms of JavaDoc or Readme?

**Comment by spencergibb** [comment]
https://github.com/spring-cloud/spring-cloud-bus/blob/master/docs/src/main/asciidoc/spring-cloud-bus.adoc

**Comment by liujiawinds** [comment]
`UnknownRemoteApplicationEvent ` that means cloud bus didn't find your customize event. ```@RemoteApplicationEventScan(basePackages = "com.maxent.bus.config")```
This annotation may help you.

**Comment by mumutu66** [comment]
I think the first point is a bug ...any unknown event will be converted to a event which will definitely cause a `NullPointerException`....
