### ISSUE TITLE
Kafka producer receive message not suit to Application Context ID

### ISSUE THREAD

**Issue by sunnyWangXin** [spring-cloud/spring-cloud-bus#77]
Hi, I use kafka in cloud bus to send/receive message, but I found that kafka producer receive the message send by itself, even though its Application Context ID not suit to destination in message. 

Example: Destination in my message is testConsumer:dev:10090, my consumer can receive and filter message as expected, but producer also receive and deal with it even ID is testProducer:dev:10080.

Below is my configuration of spring cloud bus and kafka in produces's yml. Could you help advise if anything I missed here, thanks!

`spring: 
  application: 
    name: testProducer 
   cloud: 

    bus: 
      enabled: true 
      destination: testMsgBus 
      trace: 
        enabled: true 
    stream:
      kafka:
        binder:
          brokers: localhost1:9091
          zkNodes: localhost:12183
          autoCreateTopics: true
          autoAddPartitions: true`

**Comment by spencergibb** [comment]
Duplicates #68

**Comment by sunnyWangXin** [comment]
Thanks! @spencergibb

**Comment by sunnyWangXin** [comment]
And one more question, do we have any workaround here? Something like close local event listener? or add message filter? Just my guess...Thanks.

**Comment by sunnyWangXin** [comment]
Thanks for your response, do we have any workaround now? Something like close local event listener? or add message filter? Cause I used EnvironmentChangeRemoteApplicationEvent, it will set received properties into environment directly which really hurt project.....
