### ISSUE TITLE
Inconsistent matching rules

### ISSUE THREAD

**Issue by dounine** [spring-cloud/spring-cloud-bus#80]
The /bus/refresh request is sent using postman? Destination=module1:7771 "module" module1:7772 "will restart, first started instance" module1:7771 "will also restart, third examples of" module1:7773 "," config-server "can be

**Comment by spencergibb** [comment]
A little confusing. What host did you send it to? The receiving service is always run. See #68

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
