### ISSUE TITLE
Unable to use Java 8 Time objects in RemoteApplication Events.

### ISSUE THREAD

**Issue by pmoerenhout** [spring-cloud/spring-cloud-bus#85]
I want to use Java 8 Instant objects in my custom RemoteApplicationEvents. I have the jackson-datatype-jsr310 loaded. It fails when the event is processed locally. There is no way to customize the Jackson ObjectMapper in the BusJacksonAutoConfiguration. I demonstrate it with a small sample application: https://github.com/pmoerenhout/spring-cloud-bus-custom-events. Here I overwrite the BusJacksonAutoConfiguration and use a Jackson2ObjectMapperBuilderCustomizer.
Adding this.mapper.findAndRegisterModules(); will use the Jackson JSR-310 module. The other options will allow the timezone information in a ZonedDateTime to pass along. I can make a pull request if needed.

**Comment by spencergibb** [comment]
Duplicates #95
