### ISSUE TITLE
SCB reconnect to rabbitmq, when mq cluster one node recovery

### ISSUE THREAD

**Issue by imxuthus** [spring-cloud/spring-cloud-bus#86]
hello, all
im op, i have springCloudBus exchange, type topic, features durable:true
mq cluster have 5 node.

At 10.4, one node auto restart(no any error log).
i check log , there have some error log with the node can't recover scb queue,
"Channel error on connecton ip:port -> ip:port, vhost:'/', user:'admin', channel 1: operation queue.declare caused a channel exception not_found: "no queue 'springCloudBus.anonymous.xxxxxxxxxxxxxxxx' in vhost'/' "

problem is, at rabbitmq web ui Queues tab, no any scb queue connecto to this node. but 5th node works fine, other queues connect to it.

is scb rabbitmq lib have some re blance feature? why one mq node down and recover, no scb queue to reconnect this node.

is's code problem or setting problem?

**Comment by spencergibb** [comment]
Underneath we use https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit. This question is likely better asked there.

**Comment by imxuthus** [comment]
thank you @spencergibb
