### ISSUE TITLE
how to change  the default name springCloudBus.anonymous.XXXXXXXXXXXXXX？？？

### ISSUE THREAD

**Issue by ExtremeYu** [spring-cloud/spring-cloud-bus#96]
by the way, what is the use of the springCloudBus.anonymous.XXXXXXXXXXXXXX

**Comment by spencergibb** [comment]
It is from spring-cloud-stream, which bus is built upon.

**Comment by spencergibb** [comment]
or from rabbit, if that is the binder you are using. Why do you want to change it?

**Comment by ilayaperumalg** [comment]
Hi @ExtremeYu,

This represents anonymous/single member consumer group. If you want to override, you can specify an explicit consumer group for `springCloudBus`. You can find more information about this [here](https://docs.spring.io/spring-cloud-stream/docs/Chelsea.BUILD-SNAPSHOT/reference/htmlsingle/index.html#consumer-groups)

**Comment by ExtremeYu** [comment]
@spencergibb i have configured the spring cloud stream both producer and consumer,but not set any settings about bus,should i concern the anonymous?what consequence if i dont set any property about bus？

**Comment by ExtremeYu** [comment]
@ilayaperumalg this doc is about stream ,i know how to configure stream ,but i want know the meaning about springCloudBus.anonymous

**Comment by mumutu66** [comment]
@ExtremeYu  ..Spring Cloud Bus is built upon the Spring Cloud Stream..it just defines two special 
input -> "springCloudBusInput" and output -> "springCloudBusOutput"

**Comment by ExtremeYu** [comment]
@mumutu66 恩

**Comment by baomuhedao** [comment]
他这个是广播模式，每来一个消费者，就会有个匿名乱码的队列。 消费者不需要关心具体什么队列。

**Comment by spring-issuemaster** [comment]
Closing due to age of the question. If you would like us to look at this issue, please comment and we will look at re-opening the issue.
