### ISSUE TITLE
Can not listen config changes from other services, with Spring Cloud Finchley.M2 and Spring Boot  2.0.0.M3

### ISSUE THREAD

**Issue by waylau** [spring-cloud/spring-cloud-bus#98]
I have three app services build with with Spring Cloud Finchley.M2 and Spring Boot  2.0.0.M3.

1.  `micro-weather-eureka-server` :  an Register Server, start up at port 8761.
2.  `micro-weather-config-server-bus` :  an Config Server base on  Spring Cloud Bus, start up at port 8888.
3.  `micro-weather-config-client-bus` :  an Config Client base on  Spring Cloud Bus, start up at port 8080.

All source code can find [here](https://github.com/waylau/spring-cloud-microservices-development/tree/master/samples) .

# Question

When I send l POST request at Config Server (<http://localhost:8888/application/bus/refresh>), and only the Config Server can listen config changes, but Config Client can not listen config changes from other services.

I use Rabbitmq Server v3.7.2, and I am sure Rabbitmq Server is started right.

Here are the Rabbitmq queues when my apps startup:

```
D:\rabbitmq_server-3.7.2\sbin>rabbitmqctl.bat list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / ...

springCloudBus.anonymous.mi10k6lXSbGqB2KMLf8Cwg 0
springCloudBus.anonymous.Ww1X0-RZQB6E7En7vM4J2g 0
```

Any one can help me ? I have no idea what happend. I am an new one with Spring Cloud Bus.

**Comment by spencergibb** [comment]
Please try with the latest boot (m7) and Cloud (Finchley.M5)

**Comment by waylau** [comment]
When I use Spring Cloud Bus with Spring Cloud Finchley.M5 and Spring Boot 2.0.0.M7, I can not find Bus endpoint mapping at `/bus/refresh` or `/bus-refresh`.

Here is ther [issue 99](https://github.com/spring-cloud/spring-cloud-bus/issues/99).

**Comment by waylau** [comment]
I use `management.endpoints.web.expose=*` in my app, with Spring Cloud Finchley.M5 and Spring Boot 2.0.0.M7, so I can find Bus endpoint at  `/actuator/bus-refresh`.
And I post  request at  my config server `/actuator/bus-refresh`, my config client stil doesn't refresh configeration.

**Comment by spencergibb** [comment]
Can you provide any more relevant information? Maybe a project which recreates the issue?

**Comment by spencergibb** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by sathish15g** [comment]
@waylau add   spring.bus.enabled=true in both client and server property file.
                add   management.endpoints.web.expose=bus-refresh, refresh in client will exposes /actuator/bus-refresh or /actuator/refresh api . working fine for me  refer https://github.com/sathish15g/spring-cloud-workshop  cable-internet-catalog is client application
